import book.operationsoncollections.setOpertations

fun main() {
//    week1()
//    week2()
//    basicLambda()
//    Lambda()
//    mapping()
//    joinToString()
//    lambdaAndNamedArgs()
//    twoArgLambda()
//    underscore()
//    zeroArguments()
//    filter()
//    sortingLambda()
//    closures()
//    sum()
//    creatingLists()
//    listInit()
//    predicates()
//    partition()
//    pairOfList()
//    filterNotNull()
//    byOpereations()
//    takeOrDrop()
    setOpertations()
}